### ISSUE TITLE
Support create table statement

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/HybridSE#103]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aceforeverd** [comment]
# breaking change:
`table_options`: follow zetasql's `opt_options_list` style, **current `table_options` will deprecated.**
`opt_optioins_list` is a list of (key, value) pair provided to create table statement, where `key` is Identifier (usually string)
and `value` is `expression`.

## old style
```sql
create table t1 (a int32, b string) partitionnum = 3, replicanum = 3,
     distribution = ( leader = 'l1', follower = 'fo1' );
```

## new style
```sql
create table t1 (a int32, b string) 
options (
      partitionnum = 3,
      replicanum = 3,
      distribution = [ ('le1', [ 'fo1' ]), ('le2', []), ('le3', ['fo1', 'fo2']) ]
);
```

+ `partitionnum` (case-insensitive): partition number
    - value: int
+ `replicanum` (case-insensitive): replica number
   - value: int
+ `distribution`: (case-insensiitve): partition distribution
   - value: list, list size should equal to partition number
      - schema: `[ ( leader: string, followers: [ string ] ) ]`
      - element: struct/turple of two element, first is the leader info, second is the followers info
         1. leader: endpoint. type: string literal
         2. followers: list of endpoints, type: [string literal]

**Comment by imotai** [comment]
confirmed
