### ISSUE TITLE
将varchar转成string

### ISSUE THREAD

**Issue by dl239** [4paradigm/HybridSE#193]
目前python sdk启动时会执行一些探测sql，里边有一个是包含varchar就导致编译失败，输出一些错误信息容易误导用户
![WX20210806-182842](https://user-images.githubusercontent.com/6183996/128497651-e501f0d5-9514-420e-8036-2e92d6abecc5.png)

**Comment by jingchen2222** [comment]
zetasql现在并没有支持varchar。这样需要zetasql升级一下

**Comment by jingchen2222** [comment]
1. Error messages can be optimized by [issue210](https://github.com/4paradigm/OpenMLDB/issues/210)
2. VARCHAR will be supported
