### ISSUE TITLE
macos build action

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/HybridSE#47]
**Is your feature request related to a problem? Please describe.**

run github action on MacOS environment

**Describe the solution you'd like**

- [ ] cache/upload a thirdparty artifcats, with all locked dpendencies. 
   + make sure dep like glog is available
- [ ] cmake and scripts tweaks
- [ ] build-test-report on mac

**Comment by tobegit3hub** [comment]
Currently we could not load HybridSE dynamic library in MacOS without installing `glog` dependency.

Here is the error log to load the HybridSE library in the fresh MacOS which is the Github MacOS runner.

```
21/04/20 16:18:12 INFO LibraryLoader: Found libhybridse_jsdk_core.dylib in local resource
21/04/20 16:18:16 INFO LibraryLoader: Extract resource to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/temp-3877470937410892812libhybridse_jsdk_core.dylib
21/04/20 16:18:17 ERROR LibraryLoader: Error while load libhybridse_jsdk_core.dylib from local resource
java.lang.UnsatisfiedLinkError: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/temp-3877470937410892812libhybridse_jsdk_core.dylib: dlopen(/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/temp-3877470937410892812libhybridse_jsdk_core.dylib, 1): Library not loaded: /usr/local/opt/glog/lib/libglog.0.dylib
  Referenced from: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/temp-3877470937410892812libhybridse_jsdk_core.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at com._4paradigm.hybridse.LibraryLoader.loadLibrary(LibraryLoader.java:80)
	at com._4paradigm.hybridse.HybridSeLibrary.initCore(HybridSeLibrary.java:31)
	at com._4paradigm.hybridsql.spark.SparkPlanner.<init>(SparkPlanner.scala:38)
	at com._4paradigm.hybridsql.spark.api.SparkFeSession.sparkFeSql(SparkFeSession.scala:134)
	at com._4paradigm.hybridsql.spark.api.SparkFeSession.sql(SparkFeSession.scala:147)
	at com._4paradigm.hybridsql.spark.TestUnsafeRowWindowProject.$anonfun$new$1(TestUnsafeRowWindowProject.scala:52)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
```

The complete log is in https://github.com/4paradigm/SparkFE/pull/41/checks?check_run_id=2388642188 .

**Comment by jingchen2222** [comment]
We have download thridpaty-mac.tar.gz and extract it and add the directory path into `LD_LIBRARY_PATH`. 
But still fail test. Don't know why.
@aceforeverd @tobegit3hub Could you please help to review the code.
It works well in the my local mac when I export LD_LIBRARY_PATH=thirdpath_directory_path

https://github.com/4paradigm/SparkFE/runs/2396130611?check_suite_focus=true

**Comment by vagetablechicken** [comment]
> We have download thridpaty-mac.tar.gz and extract it and add the directory path into `LD_LIBRARY_PATH`.
> But still fail test. Don't know why.
> @aceforeverd @tobegit3hub Could you please help to review the code.
> It works well in the my local mac when I export LD_LIBRARY_PATH=thirdpath_directory_path
> 
> https://github.com/4paradigm/SparkFE/runs/2396130611?check_suite_focus=true

how about `-Djava.library.path=`

**Comment by aceforeverd** [comment]
> We have download thridpaty-mac.tar.gz and extract it and add the directory path into `LD_LIBRARY_PATH`.
> But still fail test. Don't know why.
> @aceforeverd @tobegit3hub Could you please help to review the code.
> It works well in the my local mac when I export LD_LIBRARY_PATH=thirdpath_directory_path
> 
> https://github.com/4paradigm/SparkFE/runs/2396130611?check_suite_focus=true

I got a different error: https://github.com/aceforeverd/SparkFE/runs/2400230287?check_suite_focus=true#step:5:24285

**Comment by jingchen2222** [comment]
> > We have download thridpaty-mac.tar.gz and extract it and add the directory path into `LD_LIBRARY_PATH`.
> > But still fail test. Don't know why.
> > @aceforeverd @tobegit3hub Could you please help to review the code.
> > It works well in the my local mac when I export LD_LIBRARY_PATH=thirdpath_directory_path
> > https://github.com/4paradigm/SparkFE/runs/2396130611?check_suite_focus=true
> 
> how about `-Djava.library.path=`

Doesn't work either

**Comment by jingchen2222** [comment]
> > We have download thridpaty-mac.tar.gz and extract it and add the directory path into `LD_LIBRARY_PATH`.
> > But still fail test. Don't know why.
> > @aceforeverd @tobegit3hub Could you please help to review the code.
> > It works well in the my local mac when I export LD_LIBRARY_PATH=thirdpath_directory_path
> > https://github.com/4paradigm/SparkFE/runs/2396130611?check_suite_focus=true
> 
> I got a different error: https://github.com/aceforeverd/SparkFE/runs/2400230287?check_suite_focus=true#step:5:24285

Your branch is based on latest SparkFE/main. @tobegit3hub has move some cases from hybrid-sdk to sparkfe.
https://github.com/4paradigm/SparkFE/pull/38

**Comment by jingchen2222** [comment]
![image](https://user-images.githubusercontent.com/6291173/115629021-678d6780-a2b6-11eb-94f1-9ccf483fa4cc.png)
I found the env `DYLD_LIRBARY_PATH` has been set, although I export `DYLD_LIRBARY_PATH` before run mvn 
```yaml
      - name: Prepare thirdparty
        run: |
          wget http://103.3.60.66:8001/thirdparty-mac.tar.gz
          tar xzf thirdparty-mac.tar.gz -C /Users/runner/
      - name: Set LD_LIBRARY_PATH for compilation
        run: |
          echo "LD_LIBRARY_PATH=/Users/runner/thirdparty/lib" >> $GITHUB_ENV
      - name: Export LD_LIBRARY_PATH for compilation
        run: export DYLD_LIBRARY_PATH=/Users/runner/thirdparty/lib
      - name: Compile and test for MacOS
        run: |
          cd sparkfe/
          DYLD_LIBRARY_PATH=/Users/runner/thirdparty/lib mvn --settings ../tools/settings.xml -Dwagon.skip=true clean compile test -Pmacos

```
But it can be set in my local mac
![image](https://user-images.githubusercontent.com/6291173/115629396-247fc400-a2b7-11eb-89a7-1a15be3683fa.png)

```shell
DYLD_LIBRARY_PATH=/Users/chenjing/work/thirdparty/lib  mvn --settings ../tools/settings.xml -Dwagon.skip=true -Djava.library.path=/Users/chenjing/work/thirdparty/lib clean compile test -Pmacos
```

@aceforeverd Maybe we should figure out how to set env var in github mac os
I think this is why we fail test in github runner.

**Comment by aceforeverd** [comment]
we may check the source code of Java `System.LoadLibrary` ?

**Comment by jingchen2222** [comment]
```
set -e

echo "Init environment variables"

echo "DYLD_LIBRARY_PATH = ${DYLD_LIBRARY_PATH}"
export DYLD_LIBRARY_PATH=/Users/runner/thirdparty/lib

env
echo "\n" >> ~/.bash_profile
echo "DYLD_LIBRARY_PATH=/Users/runner/thirdparty/lib" >> ~/.bash_profile
source ~/.bash_profile
env

cd sparkfe/
DYLD_LIBRARY_PATH="/Users/runner/thirdparty/lib" mvn --settings ../tools/settings.xml -Dwagon.skip=true -Djava.library.path="/Users/runner/thirdparty/lib" clean compile test -Pmacos
```

**Comment by jingchen2222** [comment]
@vagetablechicken @aceforeverd Problem can be solved by:
1. remove *.dylib from `thirdparty` to prevent building with dynamic lib.
2. install glog, gflag, swig in mac for they don't have static libraries
3. install bison bin

**Comment by jingchen2222** [comment]
> ```
> set -e
> 
> echo "Init environment variables"
> 
> echo "DYLD_LIBRARY_PATH = ${DYLD_LIBRARY_PATH}"
> export DYLD_LIBRARY_PATH=/Users/runner/thirdparty/lib
> 
> env
> echo "\n" >> ~/.bash_profile
> echo "DYLD_LIBRARY_PATH=/Users/runner/thirdparty/lib" >> ~/.bash_profile
> source ~/.bash_profile
> env
> 
> cd sparkfe/
> DYLD_LIBRARY_PATH="/Users/runner/thirdparty/lib" mvn --settings ../tools/settings.xml -Dwagon.skip=true -Djava.library.path="/Users/runner/thirdparty/lib" clean compile test -Pmacos
> ```
> 
> https://github.com/4paradigm/SparkFE/pull/42/files#diff-6fa77194646a9ad7636bae39dc55d2ce9e35ffbddf10268f2b0f87bd4001e065
> 
> Try all ways to set DYLD_LIBRARY_PATH. t_t
> 
> https://github.com/4paradigm/SparkFE/runs/2407157009?check_suite_focus=true

create specific symbol link to third party lib can fix errors like "Library not loaded: /usr/local/opt/glog/lib/libglog.0.dylib"
```
ln -sf /Users/runner/thirdparty /usr/local/opt/glog
```
