### ISSUE TITLE
feat: change group id for hybridse-java module

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/HybridSE#57]
**Is your feature request related to a problem? Please describe.**
Change group id

**Describe the solution you'd like**
Use `com._4paradigm.hybridsql` as group id

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by tobegit3hub** [comment]
We have requested for this group id for central repository, refer to https://issues.sonatype.org/browse/OSSRH-68003 .
