### ISSUE TITLE
Use Zetasql as cmake dependency

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/HybridSE#59]
**Is your feature request related to a problem? Please describe.**
Although zetasql is a bazel-based project and have its dependencies in the mean time, We'll use zetasql in a cmake proeject 

**Describe the solution you'd like**
- Prepare headers
  -  find every header file and install to a include directory
    after telling cmake how to find zetasql's lib and include headers, it should link.
- compiled shared library (.so) or static library (.a)
  - find and install compiled .so/.a into same directory (without directory hierarchy)
  - for static library, using tools like `ar` or `libtool` to merge into single static archive

**Describe alternatives you've considered**
No
**Additional context**
This issue is depended on https://github.com/4paradigm/HybridSQL-docker/issues/15

**Comment by aceforeverd** [comment]
- [ ] gcc 7 -> 8
- [ ] protobuf 2 -> 3

**Comment by aceforeverd** [comment]
>     * [ ]  gcc 7 -> 8
> 
>     * [ ]  protobuf 2 -> 3

https://github.com/aceforeverd/hybridsql-asserts/tree/build/3-fix-issues
test passed used as HybridSE & zetasql-sample dependency
