### ISSUE TITLE
Build artifacts size increase greatly when move CXX_STANDARD from 14 to 17

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/HybridSE#94]
use `tools/hybridse_build.sh` as example:
the `build` directory size:
- 14: 12G
- 17: 19G

## Context (Environment)
running build on docker image `hybridsql:0.3.0` 
with
- gcc 8.3.1
- python 3.8
- openjdk 1.8

## Detailed Description

<img width="982" alt="Screen Shot 2021-05-20 at 6 45 42 PM" src="https://user-images.githubusercontent.com/11715200/118965881-b9034200-b99b-11eb-9b92-df3d52534113.png">

**Comment by jingchen2222** [comment]
We should try to reduce test bin files sizes.

**Comment by jingchen2222** [comment]
Resolved by https://github.com/4paradigm/HybridSE/pull/93
