### ISSUE TITLE
Add syntax op `&&`, `||`, `%`, `MOD`, `DIV`, `!`

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/HybridSE#99]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aceforeverd** [comment]
`||` is the ANSI standard operator for string concat

**Comment by aceforeverd** [comment]
keywords synonym
 `!`, `&&` `||`
operators:
 `div`, `mod`, `%`

add `DIV` and `MOD` keyword, reserved
